server:
  port: 8090
#  ssl:
#    key-store: file:/Users/xiaohl/Documents/work/baozi/client.p12
#    key-store-password: 12345678
#    key-store-type: PKCS12
#    key-alias: client

#spring:
#  datasource:
#    username: wenjuan
#    password: pNfSfd6FGESJkynA
##    password: 123456
#    url: jdbc:mysql://124.222.183.197:3306/wenjuan?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
##    url: jdbc:mysql://127.0.0.1:3306/wenjuan?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
#    driver-class-name: com.mysql.jdbc.Driver

spring:
  datasource:
    dynamic:
      primary: mysql #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        mysql:
          url: jdbc:mysql://124.222.183.197:3306/wenjuan?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
          username: wenjuan
          password: pNfSfd6FGESJkynA
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        individual:
          url: jdbc:mysql://124.222.183.197:3306/wenjuan?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
          username: wenjuan
          password: pNfSfd6FGESJkynA
          driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.eno.baozi.wenjuan.dao

logging:
  level:
    com:
      eno: debug
    org:
      springframework: debug
  file:
    max-size: 10MB
    max-history: 20

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
dangerous:
  report:
    path: http://www.google.com

